### ISSUE TITLE
[bug] hashing on the pi + mame .zip inside files check

### ISSUE THREAD

**Issue by giventofly** [Universal-Rom-Tools/Universal-XML-Scraper#108]
Found an issue,

i was trying to see if the problem was from the hashing here (just trying stuff), regarding my problem posted here: [games that the hash previously matched no longer match and now doing the hash of the files inside.](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/issues/101#issuecomment-269870695)

The problem is that it downloads the file list, extracts locally but trys to hash remotely (and it fails because the file doesn't exist).

http://pastebin.com/NzdsKFwF

**Comment by slydisciple** [comment]
I just finished scraping the 2000 roms that are on mame4all's game list.  It only found 39% of them and took over 18 hours because of going into the zip file.  This may, in fact, be the case... where the database only has 896 of the 2296 roms, but Im sure the database supports more.  See pic for analytics.  Im also supplying a list of game's filenames.  Thanks.
![error](https://cloud.githubusercontent.com/assets/24701204/21582097/634d787c-d010-11e6-9db4-2ccc00b18b54.PNG)
[gamelist.txt](https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/files/680091/gamelist.txt)

**Comment by Universal-Rom-Tools** [comment]
It was a problem in the API. And it's corrected now... 

Can you check and keep me up to date to know if I can close this issue ?

**Comment by giventofly** [comment]
yes, everything is working now :)

**Comment by Universal-Rom-Tools** [comment]
Great ;) I close the Issue ;)

Thank you
