### ISSUE TITLE
XML file not saving upon retropie Reboot, can't scrape PSX pbp files

### ISSUE THREAD

**Issue by Tamrowski** [Universal-Rom-Tools/Universal-XML-Scraper#140]
I get this error: 

` Could not find <gameList> node in gamelist "home/pi/.emulationstation/gamelists/gb/gamelist.xml"!`

When the scraping is complete I see the saved xml file in the system. Upon rebooting it is missing and back to a 0kb file.

When attempting to scrape PSX or PSP files the exe stops responding.

Are these known issues? As of last week the files were saving correctly. Installed the newest version to update and lost everything.

**Comment by Tamrowski** [comment]
For the moment I've fixed this by opening the file on my pc and doing a simple save of the XML file. Seems to keep the file permanently so far.

**Comment by Universal-Rom-Tools** [comment]
Don't forget to Kill Emulationstation before scraping... If you don't it don't keep your new XML File.

For PSX and PSP (big file in general) if you scrape them with network connection, it can be veeeerrrryyyy long... (I need to calculate some hash on these file, and with a network connection it "temporary" copy the file on local :( ) so it seems to freeze (but not in reality just calculating).

There is several solution for that : 
1- Scrape you big file localy ;)
2- In the scrape mode select "filename" instead of "CRC+filename"  (The problem is it's a way far less precise... and you cans, sometime, don't found a game)
3- Use the "Experimental function" in the general option. Check the check box and put the "root path" from your PI (look at the exemple). So UXS ask your PI to calculate the MD5 Hash (the fastest one) and send him back in SSH... It's faster for big file, but slower for small file.

Let's give a try to these solution and come back to tell me wich one you prefere ;)

**Comment by Universal-Rom-Tools** [comment]
No news, hope it works.

**Comment by Macothal** [comment]
I have an image with bin & cue files for psx and scraped them using UXS with no problem. I copied that image and replaced those files with PBP files. It took A VERY LONG time but I scraped these and it shows that it found all roms etc...but when I check on my pi, it just shows the names and no artwork etc... any known problems. I only put the files on the sd card as opposed to having each file in its own folder, not knowing if this makes a difference. Also, I see you say to "scrape big files locally". How are you able to do so?
