### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by Anttoonio** [Universal-Rom-Tools/Universal-XML-Scraper#143]
Hey

I found out about this program only few days ago and I'm quite new using raspberry and retropie. I installed retropie by flashing sd card with win32discimager. I downloaded image file from https://retropie.org.uk.  I have done nothing to the settings so everything is in default. Retropie image was version 4.0

So I used this UXS program which seems to be a great piece of software. I selected retropie MIX and everything seemed to go fine but when it finished and I rebooted my raspberry pi 3b I see that names of the roms are changed slightly but no pictures are showing. When I go to downloaded images folder I can see that picture files are there. I have few roms in nes ans snes folders but in both cases pictures are not working. So please if anyone could be kind enough to help me I would be greatly appericiated.

**Comment by MaryBray140** [comment]
When you're on your PC viewing your "downloaded_images" file see if you have a file directly below it called "gamelists" (Screenshot 1). If so, open it and look at each .xml file (gamelist.xml) for each of the game consoles you're adding images for. If the the files are completely "blank", you'll need to find one with the correct information (Screenshot 2) and copy& paste the file so that the Scraper can identify it.

The .xml files are like a road map for EmulationStation to identify and know where to place the images that you have downloaded.

I would also recommend that you download NotePad ++ for viewing and editing .xml, .txt files ect.
Link: https://notepad-plus-plus.org/

![screenshot 1](https://cloud.githubusercontent.com/assets/25023662/22117926/a10455fa-de2a-11e6-99e6-c7f2d945babc.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/25023662/22117932/a57dfca8-de2a-11e6-87ae-2783f0941755.png)

**Comment by Anttoonio** [comment]
Thanks for your reply.

I have one rom(donkey kong country) in snes folder. When I go to "gamelists" and from there to "snes" folder I found gamelist.xml and it looks like this.

<?xml version="1.0"?>
<gameList>
	<game>
		<path>./Donkey Kong Country I.zip</path>
		<name>Donkey Kong Country</name>
		<desc>King K. Rool has stolen Donkey Kong's banana stash, and Donkey Kong needs your help to get them back. In search of K. Rool, the Kremling horde impedes your progress. Kremlings, crocodile-like creatures, include Kritters (they succumb to a simple jump on the head), Krushas (they are virtually indestructible), and others. There are also other enemies that block your path, such as beavers, snakes, vultures. Leading them are dastardly bosses, including Very Gnawty, Necky, Bumble B, and Dumb Drum, and they all bar the way with their own special blend of villainy.

Donkey Kong is joined by Diddy Kong: these two primates differ significantly. For example, Donkey Kong is generally stronger; he can destroy most enemies with a single jump and can lift barrels straight over his head to throw them farther. On the other hand, Diddy is faster and not as strong as Donkey; he can run really fast and do cartwheels. Diddy carries barrels in front of him, creating a shield against frontal attacks.

The game is split into different worlds, which are split into different levels. Each level contains bonus areas, where one can collect bananas, medallions, and lives. At the end of each world is a boss, which is usually a larger version of a minor enemy.</desc>
		<rating>0.8</rating>
		<releasedate>19941125T000000</releasedate>
		<developer>Rareware</developer>
		<publisher>Nintendo</publisher>
		<genre>Platform</genre>
		<players>1-2</players>
		<playcount>1</playcount>
		<lastplayed>20170119T131447</lastplayed>
	</game>
</gameList>

Can you make anything out of it?

**Comment by Anttoonio** [comment]
I have no idea why but for some reason now everything is working superb :) I updated all my packages in raspberry setup. I dont know what happened but im happy now :D Sometimes it makes me feel like these computers have mind of their own. But hey thanks for your help!

**Comment by Universal-Rom-Tools** [comment]
Sorry to be late, we found a bug "cache" related on the DB website.

It's OK now.
