### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by redriche** [Universal-Rom-Tools/Universal-XML-Scraper#160]
![uxmlserror](https://cloud.githubusercontent.com/assets/24837357/22619966/fa50c70c-eabd-11e6-8eb0-bec2aa4161dd.PNG)

**Comment by MaryBray140** [comment]
First - try to completely delete the software from your system (Desktop), then re-download the software with its latest update. Give that a try and report back.

**Comment by chuckreff** [comment]
Experiencing same issue. Deleted the software from the system (Desktop), & download the latest update. Same issue. Tried in new user, same issue.

**Comment by Universal-Rom-Tools** [comment]
Hum... strange, the message is "clear" impossible to connect to the DB... Maybe due to an overload of it... (so if you hard try, maybe it would work)

Or maybe a Firewall/antivirus issue... Did you try to deactivate them ?

FYI : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/wiki/Universal-XML-Scraper-fatal-error!-(err_SystemList)

**Comment by kyotra** [comment]
I'd like to report that I've ran into the same issue, with both 32 and 64 bit versions of 2.1.0.6. I tried completely uninstalling and installing 2.1.0.5 instead, but the error is occurring with that program version too.

**Comment by Universal-Rom-Tools** [comment]
A new bigger server and a DB optimisation is in the plan... so we hope to correct these "instability" soon ...
