### ISSUE TITLE
Problem connecting to the database

### ISSUE THREAD

**Issue by jaraquistain** [Universal-Rom-Tools/Universal-XML-Scraper#170]
I was using the scraper today and it was working fine then all of a sudden an error popped up saying "Universal XML Scaper fatal error! (Problem connecting to database)"

I tried closing and re-opening the app as well as rebooting my computer.

**Comment by kjbstar** [comment]
Same here since a few days.
I had to rollback to 2.1.0.4 to be able to use the soft normally.

**Comment by Dochartaigh** [comment]
Same here today.

**Comment by Universal-Rom-Tools** [comment]
Saddly, it's a DB side problem...

I think the rollback to 2.1.0.4 is just a coincidence...

**Comment by Universal-Rom-Tools** [comment]
Sadly it's a DB side problem.

I think the 2.1.0.4 working is just a coincidence...

**Comment by morgalion** [comment]
No problem here with 2.1.0.6

**Comment by jaraquistain** [comment]
@Universal-Rom-Tools if its DB side should I close the issue?

May also be coincidence but I found that if I was repeatedly having issues connecting I could remove the entire program, re-download and it would work again.

**Comment by kjbstar** [comment]
I disagree, there's a problem. If it's not on our side (a DB issue did not mean obviously it was not client side... Especially when it happens for 15 days... Crap did I updated to a buggy version ?....), it's on DB connection side, so there's something to optimize/fix.

**Comment by Universal-Rom-Tools** [comment]
It's easy : 
The message : "Universal XML Scaper fatal error! (Problem connecting to database)" came at start when UXS can't download the systemlist.xml from ScreenScraper...

Ok, It may be not a server side issue... It may be your internet connection...
(at this moment, UXS simply do an InetGet... It's like you when you clic a link to download...)

Try to download it : https://www.screenscraper.fr/api/systemesListe.php?devid=xxx&devpassword=yyy&softname=zzz&output=XML&ssid=test&sspassword=test

**Comment by kjbstar** [comment]
Hello,

Here is a screenshot: http://img4.hostingpics.net/pics/115877screenscraper.png

* In background: the systemlist.xml
* On the left: ping and traceroute to screenscraper.fr
* On the right: same, for google.

Hops 8 and 9 are OVH and Bouygues (Overthebox ADSL Orange + 4G Free + 4G Bouygues).

Seems there is some latency to reach your server on Scaleway (hops 13 to 16).
This make me thinking the InetGet fails because of a timeout or something like that (_simple supposition, moi à part les langages du web... Mais déjà vécu des situations similaires ;)_ ).

I saw on another issue you'll soon upgrade the VM, and this other issue make me thinking I mainly tried during weekends, too. The future upgrade may help for sure.

No offense in my posts, but I'm pretty sure it's not on my side, and I just want to help to solve :)

**Comment by Universal-Rom-Tools** [comment]
No offense ^^ (but at reading, my last message is a little "hard" ^^ sorry, it's not what I want :p )

To download the systemlist, the timeout is at 40s and it try 3 time before saying "connection error".

Normally if you check in the log you must see it, something like : 
[19:46:13] - > File Downloaded Path : C:\Developpement\Github\Universal-XML-Scraper\Ressources\systemlist.xml
[19:46:13] - > -In 1 try and 1.28s

(or in you case 3 timeout)

Normally it's enough (even with a slow connection 40s for a 1Mo file...)
I can put "more" but I really think the problem is not here...

Haven't you a firewall or something like that ?

**Comment by kjbstar** [comment]
Argh, it's a mess in the folder where the scraper is, I did not see there was a log file !
I'll check it this evening, I think I still should have the connection issues in it (I tried when I was writing my previous post, there was no problem).

And yes I saw the file is only 1mo, I expected it was more but it's quite light for this kind of xml.

**Comment by Universal-Rom-Tools** [comment]
Strangely... It's seems to work ?

have you the problem right now ?

What's next in the log ? because everything seems to be downloaded and there is error...

**Comment by kjbstar** [comment]
Hooray !.... I had a timeout error lol
(First time, usually I had the database error problem).

The screenshot: http://img4.hostingpics.net/pics/921379xmltimeout.png

The Log: 

`[14:47:12] - C:\Users\kjbstar\Documents\RECALBOX\Universal_XML_Scraper64.exe (2.1.0.4)`
`[14:47:12] - WIN_10(X64) - 040C`
`[14:47:12] - Scrape in x64`
`[14:47:12] - > No updated files needed (Version : 2.1.0.4)`
`[14:47:12] - Starting files installation`
`[14:47:13] - > Ending files installation`
`[14:47:16] - > File Downloaded Path : C:\Users\kjbstar\Documents\RECALBOX\test.xml`
`[14:47:16] - > Verbose LVL : 2`
`[14:47:16] - > Path to ini : C:\Users\kjbstar\Documents\RECALBOX\UXS-config.ini`
`[14:47:16] - > Path to log : C:\Users\kjbstar\Documents\RECALBOX\LOGs\log.txt`
`[14:47:16] - > Path to language : C:\Users\kjbstar\Documents\RECALBOX\LanguageFiles`
`[14:47:16] - Language Selected : 040c`
`[14:47:16] - > Update Checking`
`[14:47:17] - > File Downloaded Path : C:\Users\kjbstar\Documents\RECALBOX\changelog.txt`
`[14:47:17] - > -In 1 try and 0.52s`
`[14:47:17] - Local : 2.1.0.4 - Github : 2.2.0.1`
`[14:47:17] - Asking to Update`
`[14:47:42] - > Timed out (20.25s) for downloading file : C:\Users\kjbstar\Documents\RECALBOX\Ressources\systemlist.xml`
`[14:48:03] - > Timed out (20.25s) for downloading file : C:\Users\kjbstar\Documents\RECALBOX\Ressources\systemlist.xml`
`[14:48:23] - > Timed out (20.25s) for downloading file : C:\Users\kjbstar\Documents\RECALBOX\Ressources\systemlist.xml`
`[14:48:23] - > -In 3 try and 61.79s`

At first I wanted to show you the log from the try I made 2 hours ago: all was OK, each file downloaded in less of 1 second each (and yes, I should install the last update ^^)

**Comment by Universal-Rom-Tools** [comment]
So I don't know if there is a bug or not ^^

Time out are Server Sided... I don't know what I can do (except put a longer time, but 20s is enough normally ... )

(And yes ;) try the new version ;) )

**Comment by Universal-Rom-Tools** [comment]
With the new version, normally all is ok now ;)
