### ISSUE TITLE
Mix image Standard (3img) - Size of Screenshot

### ISSUE THREAD

**Issue by FF-Sounds** [Universal-Rom-Tools/Universal-XML-Scraper#20]
Hi Universal-Rom-Tools,

Screenshot size is different on 3img mix since v2. It is streched on the width.

Exemple with GB system, on 1.5.11 the ratio is OK, nearly squared, but on v2 it is streched to 90% as mentionned in config.xml. (90% also mentionned in 1.5.11...) 

Is there a possibility to set the height to 85% for all system and keep the width proportional to the original ratio ?

Thanks !

![animaniacs e sgb enhanced -image](https://cloud.githubusercontent.com/assets/23526921/20395668/01aa8da2-ace4-11e6-86b8-027d06da745e.png)

![animaniacs e sgb enhanced-image](https://cloud.githubusercontent.com/assets/23526921/20395608/d0d0b22e-ace3-11e6-86b0-763bb395b2a0.png)

**Comment by Universal-Rom-Tools** [comment]
Yes, it's a bug in the new version.

Normally, the last release correct it ;)

Can you try?

thank you ;)

**Comment by FF-Sounds** [comment]
Hi !

Last release correct the size issue, agree ! thanks for that :)
It seems that a filter is applied, Is there a parameter to change in xml file to obtain a sharp screenshot ?

Maybe I demand too many things ^^

Thank you :)

![animaniacs e sgb enhanced -image](https://cloud.githubusercontent.com/assets/23526921/20437369/efc66c0c-adb3-11e6-8c2a-81d8fda39f28.png)

![animaniacs e sgb enhanced-image](https://cloud.githubusercontent.com/assets/23526921/20437377/fb2d7b26-adb3-11e6-98bc-39c1bdc6b953.png)

**Comment by Universal-Rom-Tools** [comment]
No problem ;) you never ask too much (but maybe some time I can say no ^^)

For this case... I don't know where is the problem... I didn't apply filter :S 

3 things maybe : 
* my resizing function is not so good ^^
* the final size of your picture is bigger than it was before (but if these 2 picture come directly from UXS, I think it's not the case :S )
* I use pngquant to compress png to take less disk space... but it's can reduce picture quality a little... 

I think it's the first case :S  (because the blurred screenshot haven't exactly the same size)

Need to dig in the code ^^

**Comment by Universal-Rom-Tools** [comment]
Yes ^^ I did it ;) now it's in the next release ;) I need to upload ^^

**Comment by FF-Sounds** [comment]
Yes !! Awesome ^^
Many thanks Universal-Rom-Tools !!

Bien joué :)

**Comment by Universal-Rom-Tools** [comment]
Great ^^ I close the Issue ;)
