### ISSUE TITLE
No options to save gamelist and images inside rom folder

### ISSUE THREAD

**Issue by a7mag3ddon** [Universal-Rom-Tools/Universal-XML-Scraper#213]
Just testing the new version and either i cannot find or the option to save downloaded_images and gamelist.xml inside the rom folder your scraping has gone.

Please bring it back.

**Comment by Universal-Rom-Tools** [comment]
I need to put it back ;)

But for storing your scrape in the rom folder instead of the Retropie classical folder you can just swap (in the Retropie.xml fil in ProfilsFiles Folder) : 
`<AutoConf>`  
`<Source_RootPath>\\retropie\roms</Source_RootPath>`  
`<Target_XMLName>%host%\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>`  
`<Target_RomPath>/home/pi/RetroPie/roms/%system%/</Target_RomPath>`  
`<Source_ImagePath>%host%\configs\all\emulationstation\downloaded_images\%System%</Source_ImagePath>`  
`<Target_ImagePath>/home/pi/.emulationstation/downloaded_images/%system%/</Target_ImagePath>`  
`</AutoConf>`  

With : 

`<AutoConf>`  
`<Source_RootPath>\\retropie\roms</Source_RootPath>`  
`<Target_XMLName>%Source_RootPath%\%system%\gamelist.xml</Target_XMLName>`  
`<Target_RomPath>./</Target_RomPath>`  
`<Source_ImagePath>%Source_RootPath%\%system%\downloaded_images</Source_ImagePath>`  
`<Target_ImagePath>./downloaded_images/</Target_ImagePath>`  
`</AutoConf>`  

**Source_RootPath** = The path to your rom system folder from your PC. classical Retropie is _\\retropie\roms_ But you can put an USB key for exemple like _E:\roms_

**Comment by Universal-Rom-Tools** [comment]
Test the 2.2.0.2 normally it's ok now : https://github.com/Universal-Rom-Tools/Universal-XML-Scraper/releases/tag/2.2.0.2
