### ISSUE TITLE
Scrape individual parts?

### ISSUE THREAD

**Issue by Jaxel** [Universal-Rom-Tools/Universal-XML-Scraper#216]
EmulationStation now supports some pretty complex themes. Themes where you can have multiple elements around for a single game. For instance, you can have a custom background, a video preview, a marquee, boxart, etc... Because of this, you don't really need the "Mix" feature in Universal XML Scraper anymore... since you can control all this stuff within your theme itself.

Unfortunately, Universal XML Scraper doesn't really allow you to download all these elements. It would be nice if there was a way to download snaps, boxarts, wheels, marquees and videos for each game. Instead of only the video and a mix image.

And with this of course... storing gamelist and elements in the roms folders.

**Comment by Universal-Rom-Tools** [comment]
Of course you can ;)

Just edit the Retropie.xml in ProfilsFiles folder.

Look at the exemple you found (like the "Marquee" element) : 
`	<Element Type="Marquee">`  
`		<Source_Type>XML_Download</Source_Type>`  
`		<Source_Download_Path>%Local_Path_File%</Source_Download_Path>`  
`		<Source_Download_Tag>-marquee</Source_Download_Tag>`  
`		<Source_Download_Ext>jpg</Source_Download_Ext>`  
`		<Source_Value>None</Source_Value>`  
`		<Target_Type>XML_Path</Target_Type>`  
`		<Target_Path_Type>%XML_Path_File%</Target_Path_Type>`  
`		<Target_Value>game/marquee</Target_Value>`  
`	</Element>`  

**Element Type** = Type of element like "boxart" (must be unique)
**Source_Type** = don't touch
**Source_Download_Path** = don't touch
**Source_Download_Tag** = put what you want like : "-boxart"
**Source_Download_Ext** = default extension (forced so be carreful, if you put MP3 and it's a JPG, you will have a file with MP3 as extension... but it's a JPG..)
**Source_Value** = Look at the end of the file, you will see the "option" part, with some valu you cans use like : "Data/jeu/medias/media_boxs/media_boxs2d/media_box2d_%COUNTRY%"
**Target_Type** = don't touch
**Target_Path_Type**  = don't touch
**Target_Value** = The future node of your gamelist.xml like : game/boxart

And you can create as many element you want like this...

For storing your scrape in the rom folder instead of the Retropie classical folder, I need to put an "option" to do it with the GUI.
But you can just by swaping : 
`<AutoConf>`  
`<Source_RootPath>\\retropie\roms</Source_RootPath>`  
`<Target_XMLName>%host%\configs\all\emulationstation\gamelists\%System%\gamelist.xml</Target_XMLName>`  
`<Target_RomPath>/home/pi/RetroPie/roms/%system%/</Target_RomPath>`  
`<Source_ImagePath>%host%\configs\all\emulationstation\downloaded_images\%System%</Source_ImagePath>`  
`<Target_ImagePath>/home/pi/.emulationstation/downloaded_images/%system%/</Target_ImagePath>`  
`</AutoConf>`  

With : 

`<AutoConf>`  
`<Source_RootPath>\\retropie\roms</Source_RootPath>`  
`<Target_XMLName>%Source_RootPath%\%system%\gamelist.xml</Target_XMLName>`  
`<Target_RomPath>./</Target_RomPath>`  
`<Source_ImagePath>%Source_RootPath%\%system%\downloaded_images</Source_ImagePath>`  
`<Target_ImagePath>./downloaded_images/</Target_ImagePath>`  
`</AutoConf>`  

**Source_RootPath** = The path to your rom system folder from your PC. classical Retropie is _\\retropie\roms_ But you can put an USB key for exemple like _E:\roms_

**Comment by Jaxel** [comment]
Okay, that will let me sort out the gamelist.xml.... but how do I get it do DOWNLOAD all the elements?

**Comment by Universal-Rom-Tools** [comment]
Just add as many <Element> you want ;)
It will download every Element you add :p 
Just don't forget to put a different Source_Download_Tag for each one ;)
