### ISSUE TITLE
Scrap on PC

### ISSUE THREAD

**Issue by HanaO00** [Universal-Rom-Tools/Universal-XML-Scraper#229]
I wanted to use Universal XML Scrapper for the infos of my games, I can do it directly from my PC or it is better to do it via the network?

For example I have files "MAME, GameBoy, GameBoy Color, GameBoy Advance" (island do not respect the names of recalbox but my roms are in the files, can I do it with names like that or I have to change the names the time of the scrap?

In Universal XML Scraper, in the parts "Roms paths in the XML file" I have to leave "./"? (It seems to me that it means current folder, that is it?) Path of the XML file of the blow I put the way of my roms it seems to me that it must be in the file of the roms, however the path contains my names Personal as I said "MAME, Gameboy, GameBoy Color", it does not matter? Since after I would transfer all the contents in the files

For rights on files there are specific things to do?

Do Roms have a particular name or can I name them as I want?

**Comment by Universal-Rom-Tools** [comment]
You can scrape locally on your computer, or directly on the PI or everywhere you want till you have the visibility of your rom folder from your computer.

it's easy for recalbox (little less on retropie) : the gamelist.xml and picture are stored directly in the roms folder. So "./" is ok ;)

exemple : you have a folder on your PC named : 'Gameboy Color', you can scrape it as is.
It will create the gamelist.xml and the "downloaded_picture" directly in that folder. all the path where "relative" path. So if you want to move all you roms/downloaded_picture/gamelist.xml to the "GBC" Folder on your Recalbox, it will work.

Concerning the rights, you need full rights on this folder (UXS need to READ the romfile, WRITE/DELETE the gamelist.xml, and CREATE the downloaded_picture folder.)

And for the naming convention : The best is to not rename them. because when you download a rom, it have the "standard" name. UXS look for the HASH matching first (so no problem with every name) but if not found try to match the filename. If you have renamed it wrongly, it will not work.

The Aim of scraping Rom is to create understandable gamelist. So don't worry about the name you see in Recalbox when it is scraped ;) you "sf2(u).zip" will be show as "Street Fighter 2 [USA]" (you have a lot of possible customization in the naming convention : only the name, name+option like [country] (clone, prototype, beta, demo,...), file name without extension, .... )

**Comment by HanaO00** [comment]
Thank you for your answer, so i use roms patched for my country and i want save original roms, so can i rename for example 
My original rom : Chrono Trigger (USA).sfc
And my custom rom : Chrono Trigger (PatchFR).sfc

He can recognize my custom name and scrap my custom rom ? Or i need another name ?

Thank you

**Comment by Universal-Rom-Tools** [comment]
Hum.. so many possiblities ;)

The best way : check directly on www.screenscraper.fr ;)
https://www.screenscraper.fr/gameinfos.php?gameid=2143

At the very end, you will find all Rom associated to the game.
So you can rename your original to : "Chrono Trigger (USA)" (it will work, it's in the DB ;) )
And your translated one to : "Chrono Trigger (U) [T-Fre]" or any other "standard" name for translated Rom ;)

**Comment by HanaO00** [comment]
Thank you, the extension in the Screenscraper for T-Fre is .smc, my file is .sfc, it's not a problem ?

And my custom name work ?

**Comment by Universal-Rom-Tools** [comment]
The API look for Matching filename rom without the extension ;) so no problem ;)
