### ISSUE TITLE
AutoIt Error - Subscript used on non-accessible variable

### ISSUE THREAD

**Issue by greengeek1** [Universal-Rom-Tools/Universal-XML-Scraper#234]
I am getting an error when I run the Universal_XML_Scraper.exe with the latest build on Windows 10.  This error happens randomly anywhere from within a few seconds to a few minutes after starting up the program every time.  The error is:

Autolt Error
Line 12830 (File "C:\tag\Universal_XML_Scraper.exe"):
Error: Subscript used on non-accesible variable.

I downloaded both the 32 and 64 and both are giving me the same errors.   I tried running it both with default and administrative privileges.  I also tried it without the antivirus.  I get the error every time. 

The images appear to be created correctly and it is working great up until it crashes.  The only other thing I noticed is that it appear to skip over a bunch of files that have either additional periods, apostrophes, or hyphens.

**Comment by Sined66** [comment]
Same problem with sometimes hundreds of autoit windows...
When killing the UXS process, I've a report in which I can see a 'stackhash_a1aa' module faulty (according to windows), but never on the same rom...
![uxs](https://cloud.githubusercontent.com/assets/25693038/26422503/6c355ea2-40ca-11e7-9a19-cc55d3f85bb5.png)

Launching again UXS, I'm asked to save a file with a windows called 'unknown text' in which the dialog is also 'unknown text' (with 'yes/no' butons), strange... but crashing few time later...
![uxs1](https://cloud.githubusercontent.com/assets/25693038/26422484/5a4d4c36-40ca-11e7-8730-92780a265574.png)

The problem comes with the latest version (2.2.0.2 64 bits running on win7) I downloaded to solve the problem of (Clone, Beta, Demo, ...) when missing roms.

Tried to delete all files that seems to be related to UXS, downloaded again, reboot... but no way. Downloaded images are still on the drive...

With the previous version, I'd no problem to scrape (except the 'missing rom name bug'...).

**Comment by Universal-Rom-Tools** [comment]
The unknown text isn't normal :( 
Can you delete all file in the UXS directory and "re-download" the last version ?

**Comment by greengeek1** [comment]
I did some more testing.  I get this error:

Autolt Error
Line 12830 (File "C:\tag\Universal_XML_Scraper.exe"):
Error: Subscript used on non-accesible variable.

I tried it on different systems.  I also tried it with scraping different libraries with different consoles and different roms.   This happens randomly every time.  Usually within the first 15 minutes UXS crashes.

I then tested the same libraries with the previous version of UXS, version 2.2.0.1 and every scan completed.  There we no crashes with this version.  I can confirm that this crashing bug was introduced in 2.2.0.1

**Comment by Sined66** [comment]
Reloaded a brand new fresh version, put into a new empty directory, but still have the 'stackhash_a1aa' module error (no autoit windows).
Restart then asking me to save a previously data file found (but not with the 'unknonw text' windows). Responding no then re-scrapping for a few minutes before crash (always for a different rom file).

**Comment by Warfare360** [comment]
Same issue here :(

**Comment by Universal-Rom-Tools** [comment]
I think it linked to #236 
Sorry I close this one to keep track only on one Issue ;)

Thank you guys.
