### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by mattstaten** [Universal-Rom-Tools/Universal-XML-Scraper#240]
Windows Defender detected the following malware when downloading the Universal_XML_Scraper64.exe release (as of 27 May 2017):

Trojan:Win32/Spursint.Fcl

Please address this before continuing to offer the release openly.

**Comment by greengeek1** [comment]
I downloaded both the 32bit and 64bit versions of this software and did a scan with Windows Defender in Windows 10.  It came back as the file is clean.  Also Virus Total is showing 56 out of the 61 major antivirus/malware detection systems are also showing it as clean.  With only 5 of the 61 claiming it might contain malware.  

In my experience, when you only have a few out of all the different types of anti-viruses claiming it is bad, then it is almost always a false positive.  Especially when the few that are claiming it is bad are the newer ones that are prone to give false positives, ie the ML or machine learning ones.  

You can see the results here:
https://www.virustotal.com/en/file/9a15495065c2b979b04fc92d5a2051c8cbc13e942dc1e1a8b25f2004b0452183/analysis/

**Comment by Universal-Rom-Tools** [comment]
:( sorry for that :(
The language I use (Autoit) is well know by antivirus because in the past a lots of people create malicious software with it...
So every AV block every Autoit software...
I have contacted about 30 of the main AV compagny to tell them it's a false positive.
Some respond and it's ok now with some of them... (and they confirm there is no virus)
Some never answer... And False positive is still here :'(

so you need to "accept" UXS in your AV. sorry...
(In case of doubt if there is malicious code, all sources are on the github ^^)

By security, I make some test :
https://www.virustotal.com/en/file/9a15495065c2b979b04fc92d5a2051c8cbc13e942dc1e1a8b25f2004b0452183/analysis/1495453332/
The 4 first result are "generic" Malware code... (something like : "the file want to execute an other exe, or the file access internet, or the file open XML".... And it's true ;) but it's not a malware ^^ it's the main function of UXS :p

https://virusscan.jotti.org/fr-FR/filescanjob/g4czisptuw
ClamAV detect one, but it's a well known false positive...

Tested on Kapersky too :
Résultat de l’analyse : le fichier est sain
Taille du fichier : 6,45 Мо
Type du fichier : PE64/EXE
Date d’analyse : 22 mai 2017 13:54:51
Date d’édition des bases : 22 mai 2017 11:34:53 UTC
MD5 : 2409df4503fdcc49cffcc7360870090b
SHA1 : e3a52966542fd0f8e6123c5baeda2a38440ce246
SHA256 : 9a15495065c2b979b04fc92d5a2051c8cbc13e942dc1e1a8b25f2004b0452183

And on Metadefender :
https://www.metadefender.com/#!/results/file/ZTE3MDUyMkJ5Wnh1dUdJeC1XU2tHZXVfR0xnV2I/regular/analysis

No threat found...

**Comment by hooperre** [comment]
@mattstaten Can you download the newest update and are unable to get MIX images, by chance?
