### ISSUE TITLE
Open Source ?

### ISSUE THREAD

**Issue by fOmey** [Universal-Rom-Tools/Universal-XML-Scraper#284]
I wouldn't consider this "open source", the source isn't included anywhere within this github... how are users meant to contribute to the project if we can open the project in a IDE ?

**Comment by kiryo** [comment]
I agree. With all virus flags around its pretty suspicious to keep it as "open source" in exe format at github.. not very ethical.

**Comment by Universal-Rom-Tools** [comment]
I think none of you know what Autoit Is...

All sources are on the github... You just need to own your Autoit Compiler version to compile sources...

(you  can download them on every release as "Source code (zip)" or "Source code (tar.gz)".  All sources are on the github depository. Do you know how Github work ?)

I provide compiled EXE because lot's of user don't know how to compile Autoit sources... Exemple : You don't....

So yes... It's pretty open source... Nothing to hide... Everything is here. (even the external UDF I use...)
