### ISSUE TITLE
When no data found no XML

### ISSUE THREAD

**Issue by Shampiken** [Universal-Rom-Tools/Universal-XML-Scraper#77]
Is it possible to not make an xml where there is no description and image found.
I used your wonderfull tool to scrape my snes list.
But not all snes games were found.

So I was thinking of using to slow buildin scraper for the rest of the roms that UXS didn't find.
But apparently the build-in scraper doesn't find any roms where there is nothing found.
So I guess there exists an XML even for empty findings?

**Comment by Universal-Rom-Tools** [comment]
Hi Shampiken,

It's possible to generate "empty" entry in the gamelist when nothing is found.
Just go to the "General configuration menu" and check the check box "add missing rom".

But I'm not sure it's the good way to do what you want ;)
The best way is to register to http://www.screenscraper.fr/ and submit the missing information or media to the game missing ;)

**Comment by Shampiken** [comment]
Yeah I've been looking into adding stuff.
But 200+ roms are kinda alot :)

Also it seems it doesn't find some roms because checksum isn't corresponding. But when I look at it through filename it doesn't find some data either.

Ah well I'll look into it a bit more.

**Comment by Universal-Rom-Tools** [comment]
UXS works like this : 
Calculate Hash for you rom
Try to find a Match in the DB by Hash
If not
Try to find a Match in the DB by Filename

The problem is, if you rename your rom, the DB may have not the same name (we add a lot's of roms, but it's impossible to add every variation). The simple way is to have "standard" roms, like no-intro, tosec, goodxxx romset, or at least, the naming convention of them ;)

**Comment by Shampiken** [comment]
Yeah.
That's actually a great plan to try! :)
I'll lookup for the snes no-intro right away.

**Comment by Shampiken** [comment]
When using the no-intro set it worked as a charm ;)

**Comment by Universal-Rom-Tools** [comment]
Great 👍  I clos the Issue
